version: "3.5"
services:
  freqtrade.dnp.dappnode.eth:
    image: "freqtrade.dnp.dappnode.eth:0.1.0"
    build:
      context: build
    volumes:
      - "freqtrade:/freqtrade/user_data"
    restart: unless-stopped
volumes:
  freqtrade: {}
